# 开发环境连接参数直接填写在本文件。
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/qc_meta?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username=qc_meta
spring.datasource.password=Bq92zuJZVeCXGrfgWPv5mgtMCZIR4Y8y
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=10000
