# \u586B\u5199 beta \u7684\u5B9E\u9645\u8FDE\u63A5\u53C2\u6570\u540E\u542F\u52A8\uFF0C\u4E0D\u80FD\u6CBF\u7528 dev \u7684\u8FDE\u63A5\u4FE1\u606F\u3002
spring.datasource.url=jdbc:mysql://10.162.12.160:13511/qclog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
spring.datasource.username=qclog
spring.datasource.password=qclog_pwd
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=10000
